# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "AGED" ("ID" INTEGER NOT NULL PRIMARY KEY,"NAME" CHAR(255) NOT NULL,"KANA" CHAR(255) NOT NULL,"AGE" TINYINT NOT NULL,"SEX" CHAR(4) NOT NULL,"BIRTHED" DATE NOT NULL,"ADDRESS" CHAR(65535) NOT NULL,"POSTAL" CHAR(7) NOT NULL,"PHONNE" CHAR(13) NOT NULL,"INSURANCE_ID" INTEGER NOT NULL,"HOME_ID" INTEGER NOT NULL,"LEFT" DATE NOT NULL);
create index "AGED_INDEX" on "AGED" ("ID");
create table "HOMES" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"CORPORATION_NAME" CHAR(255) NOT NULL,"OFFICE_NAME" CHAR(255) NOT NULL,"CARE_TYPE" CHAR(255) NOT NULL);
create index "HOMES_INDEX" on "HOMES" ("ID");
create table "INSURANCES" ("ID" INTEGER NOT NULL PRIMARY KEY,"LEVEL" TINYINT NOT NULL,"STARTED" DATE NOT NULL,"EXPIRES" DATE NOT NULL,"AGED_ID" INTEGER NOT NULL);
create index "INSURANCE_INDEX" on "INSURANCES" ("ID");
alter table "AGED" add constraint "HOME_FK" foreign key("HOME_ID") references "HOMES"("ID") on update CASCADE on delete RESTRICT;
alter table "AGED" add constraint "INSURANCE_FK" foreign key("INSURANCE_ID") references "INSURANCES"("ID") on update CASCADE on delete RESTRICT;
alter table "INSURANCES" add constraint "AGED_FK" foreign key("AGED_ID") references "AGED"("ID") on update CASCADE on delete CASCADE;

# --- !Downs

alter table "INSURANCES" drop constraint "AGED_FK";
alter table "AGED" drop constraint "HOME_FK";
alter table "AGED" drop constraint "INSURANCE_FK";
drop table "INSURANCES";
drop table "HOMES";
drop table "AGED";

